stereo_camera_node:
  ros__parameters:
    target_fps: 19.8
    duration_sec: 10.0
    exposure_us: 30000.0
    gain_db: 18.0
    output_dir: "."
    buffer_timeout: 3000
    lut_enable: true
    lut_sigmoid_threshold: 0.005
    lut_sigmoid_strength: 20.0
    lut_sigmoid_dark_limit: 0
    lut_sigmoid_bright_limit: 4095
    sync_tolerance_us: 5000.0
